imports:
    - { resource: config_test.yml }

framework:
    profiler:
        only_exceptions: false
        collect: true

web_profiler:
    toolbar: true

doctrine:
    dbal:
        dbname: "%database_name%_acceptance"

csa_guzzle:
    logger: true
    clients:
        local_test_api:
            config:
                base_url: http://139.59.189.171:8080/web/app_acceptance.php/